import { Product, ProductCategory } from '@/types'

export const productCategories: ProductCategory[] = [
  {
    id: 'sweet-treats',
    name: 'Sweet Protein Treats',
    slug: 'sweet-treats',
    description: 'Guilt-free nutritional treats that perfectly balance taste and health',
    image: '/api/placeholder/400/300',
  },
  {
    id: 'natural-foods',
    name: 'Protein Rich Natural Foods',
    slug: 'natural-foods',
    description: 'Protein shakes, instant porridge mixes, curry & spice mixes, dosa/crepe mixes',
    image: '/api/placeholder/400/300',
  },
  {
    id: 'savory-treats',
    name: 'Savory Protein Treats',
    slug: 'savory-treats',
    description: 'Nutrient-packed options supporting your active lifestyle',
    image: '/api/placeholder/400/300',
  },
]

export const products: Product[] = [
  // Sweet Protein Treats
  {
    id: '1',
    name: 'Biotin Bites',
    description: 'Nutritious sweet bites enriched with biotin for healthy hair, skin, and nails',
    price: 299,
    category: productCategories[0],
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400'],
    ingredients: ['Almonds', 'Dates', 'Biotin', 'Natural Sweeteners'],
    nutritionalInfo: {
      protein: 12,
      carbs: 25,
      fat: 8,
      fiber: 4,
      calories: 220,
      servingSize: '30g',
    },
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    stock: 50,
    featured: true,
  },
  {
    id: '2',
    name: 'Nutty Fruit Bites',
    description: 'Delicious combination of nuts and dried fruits for natural energy',
    price: 249,
    category: productCategories[0],
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400'],
    ingredients: ['Mixed Nuts', 'Dried Fruits', 'Honey', 'Coconut'],
    nutritionalInfo: {
      protein: 10,
      carbs: 22,
      fat: 12,
      fiber: 5,
      calories: 240,
      servingSize: '35g',
    },
    isGlutenFree: true,
    isVegan: false,
    isOrganic: true,
    stock: 45,
    featured: true,
  },
  
  // Protein Rich Natural Foods
  {
    id: '3',
    name: 'Protein Power Shake Mix',
    description: 'Complete protein blend for muscle building and recovery',
    price: 599,
    category: productCategories[1],
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400'],
    ingredients: ['Pea Protein', 'Brown Rice Protein', 'Natural Flavors', 'Vitamins'],
    nutritionalInfo: {
      protein: 25,
      carbs: 8,
      fat: 3,
      fiber: 2,
      calories: 150,
      servingSize: '30g',
    },
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    stock: 30,
    featured: true,
  },
  {
    id: '4',
    name: 'Instant Porridge Mix',
    description: 'Wholesome breakfast option with complete nutrition',
    price: 199,
    category: productCategories[1],
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400'],
    ingredients: ['Rolled Oats', 'Quinoa', 'Chia Seeds', 'Natural Flavors'],
    nutritionalInfo: {
      protein: 8,
      carbs: 35,
      fat: 4,
      fiber: 6,
      calories: 200,
      servingSize: '50g',
    },
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    stock: 60,
    featured: false,
  },
  {
    id: '5',
    name: 'Curry & Spice Mix',
    description: 'Authentic Indian spice blends for flavorful healthy meals',
    price: 149,
    category: productCategories[1],
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400'],
    ingredients: ['Turmeric', 'Cumin', 'Coriander', 'Red Chili', 'Garam Masala'],
    nutritionalInfo: {
      protein: 2,
      carbs: 8,
      fat: 1,
      fiber: 3,
      calories: 50,
      servingSize: '10g',
    },
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    stock: 80,
    featured: false,
  },
  {
    id: '6',
    name: 'Dosa & Crepe Mix',
    description: 'Traditional South Indian breakfast made easy and nutritious',
    price: 179,
    category: productCategories[1],
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400'],
    ingredients: ['Rice Flour', 'Lentil Flour', 'Fenugreek', 'Salt'],
    nutritionalInfo: {
      protein: 6,
      carbs: 40,
      fat: 2,
      fiber: 4,
      calories: 200,
      servingSize: '50g',
    },
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    stock: 40,
    featured: false,
  },

  // Savory Protein Treats
  {
    id: '7',
    name: 'Protein Chips',
    description: 'Crunchy, healthy chips packed with plant-based protein',
    price: 199,
    category: productCategories[2],
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400'],
    ingredients: ['Chickpea Flour', 'Lentil Flour', 'Spices', 'Himalayan Salt'],
    nutritionalInfo: {
      protein: 15,
      carbs: 20,
      fat: 6,
      fiber: 5,
      calories: 180,
      servingSize: '30g',
    },
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    stock: 35,
    featured: true,
  },
  {
    id: '8',
    name: 'Protein Murukulu',
    description: 'Traditional South Indian snack with added protein benefits',
    price: 229,
    category: productCategories[2],
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400'],
    ingredients: ['Rice Flour', 'Lentil Flour', 'Sesame Seeds', 'Cumin', 'Asafoetida'],
    nutritionalInfo: {
      protein: 12,
      carbs: 28,
      fat: 8,
      fiber: 3,
      calories: 220,
      servingSize: '35g',
    },
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    stock: 25,
    featured: true,
  },
  {
    id: '9',
    name: 'Instant Sambar Mix',
    description: 'Ready-to-cook traditional South Indian lentil curry',
    price: 179,
    category: productCategories[2],
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400'],
    ingredients: ['Toor Dal', 'Tamarind', 'Sambar Powder', 'Turmeric', 'Salt'],
    nutritionalInfo: {
      protein: 8,
      carbs: 25,
      fat: 2,
      fiber: 6,
      calories: 140,
      servingSize: '40g',
    },
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    stock: 55,
    featured: false,
  },
]

export const getFeaturedProducts = () => products.filter(product => product.featured)

export const getProductsByCategory = (categoryId: string) => 
  products.filter(product => product.category.id === categoryId)

export const getProductById = (id: string) => 
  products.find(product => product.id === id)