import { Product, ProductCategory } from '@/types/product'

export function getAllProducts(): Product[] {
  return products
}

export function getProductById(id: string): Product | undefined {
  return products.find(product => product.id === id)
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter(product => product.category.id === categoryId)
}

export const productCategories: ProductCategory[] = [
  {
    id: 'sweet-treats',
    name: 'Sweet Protein Treats',
    slug: 'sweet-treats',
    description: 'Guilt-free nutritional treats that perfectly balance taste and health',
    image: 'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=300&fit=crop&crop=center',
  },
  {
    id: 'natural-foods',
    name: 'Protein Rich Natural Foods',
    slug: 'natural-foods',
    description: 'Protein shakes, instant porridge mixes, curry & spice mixes, dosa/crepe mixes',
    image: 'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=300&fit=crop&crop=center',
  },
  {
    id: 'savory-treats',
    name: 'Savory Protein Treats',
    slug: 'savory-treats',
    description: 'Nutrient-packed options supporting your active lifestyle',
    image: 'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=300&fit=crop&crop=center',
  },
]

export const products: Product[] = [
  // Sweet Protein Treats
  {
    id: '1',
    name: 'Biotin Bites',
    description: 'Nutritious sweet bites enriched with biotin for healthy hair, skin, and nails',
    price: 299,
    originalPrice: 349,
    images: [
      'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=400&fit=crop&crop=center',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center'
    ],
    category: productCategories[0],
    tags: ['biotin', 'sweet', 'bites'],
    ingredients: ['Almonds', 'Dates', 'Biotin', 'Natural Sweeteners'],
    nutritionalInfo: {
      protein: 12,
      carbs: 25,
      fat: 8,
      fiber: 4,
      calories: 220,
      servingSize: '30g',
      servingsPerContainer: 10,
      sugar: 10,
      sodium: 30,
      iron: 2,
      calcium: 20,
      potassium: 100,
      vitaminC: 0
    },
    allergens: ['nuts'],
    certifications: ['organic'],
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    isKeto: false,
    isDairy: false,
    stock: 50,
    featured: true,
    averageRating: 4.7,
    reviewCount: 120,
    preparationTime: 'Ready to eat',
    shelfLife: '12 months',
    storageInstructions: 'Store in a cool, dry place',
    servingSuggestions: ['Enjoy as a snack', 'Add to yogurt'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
    variants: [],
  },
  {
    id: '2',
    name: 'Nutty Fruit Bites',
    description: 'Delicious combination of nuts and dried fruits for natural energy',
    price: 249,
    originalPrice: 299,
    images: [
      'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=400&fit=crop&crop=center',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center'
    ],
    category: productCategories[0],
    tags: ['nutty', 'fruit', 'bites'],
    ingredients: ['Mixed Nuts', 'Dried Fruits', 'Honey', 'Coconut'],
    nutritionalInfo: {
      protein: 10,
      carbs: 22,
      fat: 12,
      fiber: 5,
      calories: 240,
      servingSize: '35g',
      servingsPerContainer: 8,
      sugar: 15,
      sodium: 20,
      iron: 1,
      calcium: 15,
      potassium: 80,
      vitaminC: 0
    },
    allergens: ['nuts'],
    certifications: ['organic'],
    isGlutenFree: true,
    isVegan: false,
    isOrganic: true,
    isKeto: false,
    isDairy: false,
    stock: 45,
    featured: true,
    averageRating: 4.5,
    reviewCount: 90,
    preparationTime: 'Ready to eat',
    shelfLife: '10 months',
    storageInstructions: 'Store in a cool, dry place',
    servingSuggestions: ['Snack on the go', 'Add to oatmeal'],
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-11T00:00:00Z',
    variants: [],
  },
  
  // Protein Rich Natural Foods
  {
    id: '3',
    name: 'Protein Power Shake Mix',
    description: 'Complete protein blend for muscle building and recovery',
    price: 599,
    originalPrice: 699,
    images: [
      'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=400&fit=crop&crop=center',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center'
    ],
    category: productCategories[1],
    tags: ['protein', 'shake', 'blend'],
    ingredients: ['Pea Protein', 'Brown Rice Protein', 'Natural Flavors', 'Vitamins'],
    nutritionalInfo: {
      protein: 25,
      carbs: 8,
      fat: 3,
      fiber: 2,
      calories: 150,
      servingSize: '30g',
      servingsPerContainer: 12,
      sugar: 5,
      sodium: 15,
      iron: 2,
      calcium: 10,
      potassium: 50,
      vitaminC: 0
    },
    allergens: ['soy'],
    certifications: ['vegan'],
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    isKeto: false,
    isDairy: false,
    stock: 30,
    featured: true,
    averageRating: 4.8,
    reviewCount: 110,
    preparationTime: 'Mix instantly',
    shelfLife: '18 months',
    storageInstructions: 'Keep sealed in a cool, dry place',
    servingSuggestions: ['Blend with water', 'Add to smoothie'],
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-12T00:00:00Z',
    variants: [],
  },
  {
    id: '4',
    name: 'Instant Porridge Mix',
    description: 'Wholesome breakfast option with complete nutrition',
    price: 199,
    originalPrice: 249,
    images: [
      'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=400&fit=crop&crop=center',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center'
    ],
    category: productCategories[1],
    tags: ['porridge', 'breakfast', 'mix'],
    ingredients: ['Rolled Oats', 'Quinoa', 'Chia Seeds', 'Natural Flavors'],
    nutritionalInfo: {
      protein: 8,
      carbs: 35,
      fat: 4,
      fiber: 6,
      calories: 200,
      servingSize: '50g',
      servingsPerContainer: 10,
      sugar: 8,
      sodium: 25,
      iron: 1,
      calcium: 8,
      potassium: 30,
      vitaminC: 0
    },
    allergens: ['oats'],
    certifications: ['gluten-free'],
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    isKeto: false,
    isDairy: false,
    stock: 60,
    featured: false,
    averageRating: 4.3,
    reviewCount: 80,
    preparationTime: '2 min',
    shelfLife: '12 months',
    storageInstructions: 'Store in a cool, dry place',
    servingSuggestions: ['Add hot water', 'Top with fruit'],
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2024-01-13T00:00:00Z',
    variants: [],
  },
  {
    id: '5',
    name: 'Curry & Spice Mix',
    description: 'Authentic Indian spice blends for flavorful healthy meals',
    price: 149,
    originalPrice: 199,
    images: [
      'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=400&fit=crop&crop=center',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center'
    ],
    category: productCategories[1],
    tags: ['curry', 'spice', 'mix'],
    ingredients: ['Turmeric', 'Cumin', 'Coriander', 'Red Chili', 'Garam Masala'],
    nutritionalInfo: {
      protein: 2,
      carbs: 8,
      fat: 1,
      fiber: 3,
      calories: 50,
      servingSize: '10g',
      servingsPerContainer: 15,
      sugar: 2,
      sodium: 10,
      iron: 0.5,
      calcium: 2,
      potassium: 10,
      vitaminC: 0
    },
    allergens: [],
    certifications: ['vegan'],
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    isKeto: true,
    isDairy: false,
    stock: 80,
    featured: false,
    averageRating: 4.2,
    reviewCount: 60,
    preparationTime: 'Ready to cook',
    shelfLife: '24 months',
    storageInstructions: 'Keep sealed',
    servingSuggestions: ['Add to curries', 'Use as seasoning'],
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-14T00:00:00Z',
    variants: [],
  },
  {
    id: '6',
    name: 'Dosa & Crepe Mix',
    description: 'Traditional South Indian breakfast made easy and nutritious',
    price: 179,
    originalPrice: 229,
    images: [
      'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=400&fit=crop&crop=center',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center'
    ],
    category: productCategories[1],
    tags: ['dosa', 'crepe', 'mix'],
    ingredients: ['Rice Flour', 'Lentil Flour', 'Fenugreek', 'Salt'],
    nutritionalInfo: {
      protein: 6,
      carbs: 40,
      fat: 2,
      fiber: 4,
      calories: 200,
      servingSize: '50g',
      servingsPerContainer: 8,
      sugar: 7,
      sodium: 18,
      iron: 1,
      calcium: 6,
      potassium: 20,
      vitaminC: 0
    },
    allergens: ['lentils'],
    certifications: ['gluten-free'],
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    isKeto: false,
    isDairy: false,
    stock: 40,
    featured: false,
    averageRating: 4.4,
    reviewCount: 70,
    preparationTime: '5 min',
    shelfLife: '10 months',
    storageInstructions: 'Store in a cool, dry place',
    servingSuggestions: ['Make dosas', 'Make crepes'],
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
    variants: [],
  },

  // Savory Protein Treats
  {
    id: '7',
    name: 'Protein Chips',
    description: 'Crunchy, healthy chips packed with plant-based protein',
    price: 199,
    originalPrice: 249,
    images: [
      'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=400&fit=crop&crop=center',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center'
    ],
    category: productCategories[2],
    tags: ['chips', 'protein', 'snack'],
    ingredients: ['Chickpea Flour', 'Lentil Flour', 'Spices', 'Himalayan Salt'],
    nutritionalInfo: {
      protein: 15,
      carbs: 20,
      fat: 6,
      fiber: 5,
      calories: 180,
      servingSize: '30g',
      servingsPerContainer: 10,
      sugar: 6,
      sodium: 22,
      iron: 1.5,
      calcium: 7,
      potassium: 25,
      vitaminC: 0
    },
    allergens: ['chickpeas'],
    certifications: ['vegan'],
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    isKeto: true,
    isDairy: false,
    stock: 35,
    featured: true,
    averageRating: 4.6,
    reviewCount: 95,
    preparationTime: 'Ready to eat',
    shelfLife: '8 months',
    storageInstructions: 'Keep sealed',
    servingSuggestions: ['Eat as snack', 'Add to salad'],
    createdAt: '2024-01-07T00:00:00Z',
    updatedAt: '2024-01-16T00:00:00Z',
    variants: [],
  },
  {
    id: '8',
    name: 'Protein Murukulu',
    description: 'Traditional South Indian snack with added protein benefits',
    price: 229,
    originalPrice: 279,
    images: [
      'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=400&fit=crop&crop=center',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center'
    ],
    category: productCategories[2],
    tags: ['murukulu', 'protein', 'snack'],
    ingredients: ['Rice Flour', 'Lentil Flour', 'Sesame Seeds', 'Cumin', 'Asafoetida'],
    nutritionalInfo: {
      protein: 12,
      carbs: 28,
      fat: 8,
      fiber: 3,
      calories: 220,
      servingSize: '35g',
      servingsPerContainer: 10,
      sugar: 10,
      sodium: 30,
      iron: 2,
      calcium: 20,
      potassium: 100,
      vitaminC: 0
    },
    allergens: ['sesame'],
    certifications: ['vegan'],
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    isKeto: false,
    isDairy: false,
    stock: 25,
    featured: true,
    averageRating: 4.5,
    reviewCount: 85,
    preparationTime: 'Ready to eat',
    shelfLife: '10 months',
    storageInstructions: 'Store in airtight container',
    servingSuggestions: ['Eat as snack', 'Serve with tea'],
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-17T00:00:00Z',
    variants: [],
  },
  {
    id: '9',
    name: 'Instant Sambar Mix',
    description: 'Ready-to-cook traditional South Indian lentil curry',
    price: 179,
    originalPrice: 229,
    images: [
      'https://images.unsplash.com/photo-1599599810694-57a2ca9f5a94?w=400&h=400&fit=crop&crop=center',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center'
    ],
    category: productCategories[2],
    tags: ['sambar', 'mix', 'lentil'],
    ingredients: ['Toor Dal', 'Tamarind', 'Sambar Powder', 'Turmeric', 'Salt'],
    nutritionalInfo: {
      protein: 8,
      carbs: 25,
      fat: 2,
      fiber: 6,
      calories: 140,
      servingSize: '40g',
      servingsPerContainer: 10,
      sugar: 8,
      sodium: 25,
      iron: 1,
      calcium: 8,
      potassium: 30,
      vitaminC: 0
    },
    allergens: ['toor dal'],
    certifications: ['vegan'],
    isGlutenFree: true,
    isVegan: true,
    isOrganic: true,
    isKeto: false,
    isDairy: false,
    stock: 55,
    featured: false,
    averageRating: 4.1,
    reviewCount: 60,
    preparationTime: '5 min',
    shelfLife: '12 months',
    storageInstructions: 'Store in a cool, dry place',
    servingSuggestions: ['Serve with rice', 'Use as soup base'],
    createdAt: '2024-01-09T00:00:00Z',
    updatedAt: '2024-01-18T00:00:00Z',
    variants: [],
  },
]

export const getFeaturedProducts = () => products.filter(product => product.featured)